### ISSUE TITLE
Investigate unhandled promise rejections

### ISSUE THREAD

**Issue by ricktjwong** [opendocsg/pdf-to-markdown#11]
Running the pdf2md converter throws a `UnhandledPromiseRejectionWarning: ReferenceError: document is not defined` error. This is hypothesised to be the cause of some font differences between the browser and the CLI version.

Investigate and solve the problem.

**Comment by LoneRifle** [comment]
Possible first stab at the problem: https://github.com/mozilla/pdf.js/blob/master/examples/node/domstubs.js
