### ISSUE TITLE
Resolve bugs

### ISSUE THREAD

**Issue by ricktjwong** [opendocsg/pdf-to-markdown#14]
- [x] Unsupported headline level: 7 (supported are 1-6) - This arises when a text detected from PDF is smaller than what is supported by markdown (H6). This error terminates the entire program and crashes inelegantly.
- [x] Warning: Native JPEG decoding failed -- trying to recover: Image is not defined - arises because of the missing Image.proptotype which exists in browser. Need to stub this as well. Didn't have to remove the Image.prototype previously.
- [x] TypeError: Cannot read property 'items' of undefined - arises from models/transformations/lineitem/DetectTOC.jsx
- [ ] ~'UnknownErrorException', message: 'Illegal character: 41' - arises from the Singapore European Free Trade Association Legal Text folder~ filed as new issue, TBD

**Comment by LoneRifle** [comment]
@ricktjwong can you file a new issue for the 4th bug please?
